import { fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, expect, it, vi } from 'vitest'
import App from './App'
import { executionFixture, manifestFixture } from './test/fixtures'
const response = (value: unknown) => new Response(JSON.stringify(value), {status:200})
beforeEach(() => {
  window.history.replaceState({}, '', '?renderer=legacy')
  vi.stubGlobal('matchMedia', vi.fn(() => ({ matches:false, addEventListener:vi.fn(), removeEventListener:vi.fn() })))
})
async function seat(user: ReturnType<typeof userEvent.setup>) {
  await user.click(await screen.findByRole('button',{name:'Open the Arca'}))
  await user.click(screen.getByRole('button',{name:/DODECAMORIVM/}))
  await user.click(screen.getByRole('button',{name:/Open Cell IV/}))
  await user.click(screen.getByRole('button',{name:/Lift.*critical-edition carrier/i}))
  expect(screen.getByRole('button',{name:/Seat the carrier/i})).toBeEnabled()
  expect(screen.getByRole('button',{name:/LECTIO/})).toBeDisabled()
  await user.click(screen.getByRole('button',{name:/Seat the carrier/i}))
}
it('completes a v2 legacy reading, preserving carrier and cursor on return', async () => {
  const fetchMock = vi.fn().mockResolvedValueOnce(response(manifestFixture)).mockResolvedValueOnce(response(executionFixture))
  vi.stubGlobal('fetch',fetchMock)
  const user = userEvent.setup()
  const {container} = render(<App />)
  await seat(user)
  fireEvent.change(screen.getByRole('slider'),{target:{value:'5'}})
  const id = container.querySelector('[data-instance-id]')?.getAttribute('data-instance-id')
  await user.click(screen.getByRole('button',{name:/LECTIO/}))
  await screen.findByText('Four voices manifest')
  expect(screen.getByRole('table',{name:'Symbolic historical four-voice result'})).toBeVisible()
  const body = JSON.parse(fetchMock.mock.calls[1][1].body)
  expect(Object.keys(body).sort()).toEqual(['carrier_instance','content_digest','format','manifest_id'])
  expect(body.carrier_instance.instance_id).toBe(id)
  expect(body.format).toBe('neo-arca-mechanica-reading/v2')
  await user.click(screen.getByRole('button',{name:/Return to/}))
  expect(screen.getByRole('slider')).toHaveValue('5')
  expect(container.querySelector('[data-instance-id]')).toHaveAttribute('data-instance-id',id)
  expect(fetchMock).toHaveBeenCalledTimes(2)
})
it('keeps the reading on error and retries without duplicating the carrier', async () => {
  const fetchMock = vi.fn().mockResolvedValueOnce(response(manifestFixture))
    .mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(response(executionFixture))
  vi.stubGlobal('fetch',fetchMock)
  const user = userEvent.setup()
  render(<App />)
  await seat(user)
  await user.click(screen.getByRole('button',{name:/LECTIO/}))
  expect(await screen.findByRole('alert')).toHaveTextContent('offline')
  await user.click(screen.getByRole('button',{name:/LECTIO/}))
  await screen.findByText('Four voices manifest')
  expect(fetchMock.mock.calls[1][1].body).toBe(fetchMock.mock.calls[2][1].body)
})
it('rejects a stale server manifest clearly',async () => {
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response({format:'neo-arca-mechanica-manifest/v1'})))
  render(<App />)
  expect(await screen.findByRole('alert')).toHaveTextContent(/contract/i)
})
it('propagates reduced motion and keeps presentation realm out of requests',async () => {
  vi.stubGlobal('matchMedia',vi.fn(() => ({matches:true,addEventListener:vi.fn(),removeEventListener:vi.fn()})))
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response(manifestFixture)))
  const {container}=render(<App />)
  await screen.findByRole('button',{name:'Open the Arca'})
  expect(container.querySelector('.instrument-shell')).toHaveAttribute('data-reduced-motion','true')
  expect(container.querySelector('.instrument-shell')).toHaveAttribute('data-realm','historica')
})
